name: base

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python == 3.11.4
  - xesmf
  - ipykernel
  - ipywidgets
  - nb_conda_kernels
  - pytest
  - gsw
  - cmcrameri
  - pip
  - pip:
      - cartopy
      - matplotlib
      - seaborn
      - geopy
      - basemap
      - netcdf4
      - jupyter
      - scipy
      - jupyterlab
      - jupyter_contrib_nbextensions
      - dask
      - dask-labextension
      - nc-time-axis
      - xlrd
      - plotly
      - requests
      - nodejs
      - pythreejs
      - bqplot
      - psyplot
      - psy-maps 
      - psyplot-gui 
      - psy-reg 
      - cdsapi 
      - basemap-data-hires
      - cdo
      - nco
      - jupytext
      - pydap
      - geonum
      - gcsfs
      - ecgtools
      - intake
      - intake-esm
      - ipydatawidgets
      - sidecar
      - geojsoncontour
      - scientific-colourmaps
      - spei